### ISSUE TITLE
Cannot 'cast' lambda group to some FunctionX interface

### ISSUE THREAD

**Issue by heckej** [heckej/proguard#12]
# Problem

In some JVM's the lambda groups cannot be cast to the type that they implement (e.g. `kotlin.jvm.functions.Function3`), even though they do implement the interface and the necessary methods.

# Cause of the problem

The cause of this problem might be the fact that the lambda groups don't contain any generics information. The 
[JVM classfile specification](https://docs.oracle.com/javase/specs/jvms/se11/html/jvms-4.html#jvms-4.7.9.1) describes what signature attributes are needed w.r.t. generics or parametrisation.

# Proposed solution

* Read the JVM classfile specification w.r.t. generics
* Add the necessary signature attributes to the lambda groups

**Comment by heckej** [comment]
Note: R8 doesn't add any signature attributes to lambda groups.
TODO: test whether the same app optimised with R8 throws the same (or comparable) casting exceptions.

**Comment by heckej** [comment]
This issue probably occurs in situations like the following (in decompiled code)

```lang=java
public static Function2<Composer, Integer, Unit> f0lambda1 = ComposableLambdaKt.composableLambdaInstance(-985532999, false, new LambdaGroup(0));
```

where explicit generic parameter types are used. Decompilation of the original code contained this line:

```
public static Function2<Composer, Integer, Unit> f0lambda1 = ComposableLambdaKt.composableLambdaInstance(-985532999, false, ComposableSingletons$FileTreeViewKt$lambda1$1.INSTANCE);
```
where the referenced lambda class has the following signature:

```
final class ComposableSingletons$FileTreeViewKt$lambda1$1 extends Lambda implements Function2<Composer, Integer, Unit>
```

**Comment by heckej** [comment]
The questions that arises from the previous example are the following:

* does a lambda group have to contain the attributes for `Function2<Composer, Integer, Unit>`?
* or would it suffice to contain the broader `Function2<Object, Object, Object>`?

**Comment by heckej** [comment]
> or would it suffice to contain the broader `Function2<Object, Object, Object>`?

This does not seem to suffice.

**Comment by heckej** [comment]
More detailed information about the bug for the application [ComposeCodeViewer](https://github.com/JetBrains/compose-jb/tree/master/examples/codeviewer): 
Part of the stack trace:

```
Exception in thread "AWT-EventQueue-0" java.lang.ClassCastException: org.jetbrains.codeviewer.ui.filetree.LambdaGroup cannot be cast to kotlin.jvm.functions.Function2
        at androidx.compose.runtime.internal.ComposableLambdaImpl.invoke(ComposableLambda.jvm.kt:107)
        at androidx.compose.runtime.internal.ComposableLambdaImpl.invoke(ComposableLambda.jvm.kt:34)
        at androidx.compose.material.SurfaceKt$Surface$6.invoke(Surface.kt:268)
        at androidx.compose.material.SurfaceKt$Surface$6.invoke(Surface.kt:255)
        at androidx.compose.runtime.internal.ComposableLambdaImpl.invoke(ComposableLambda.jvm.kt:107)
        at androidx.compose.runtime.internal.ComposableLambdaImpl.invoke(ComposableLambda.jvm.kt:34)
        at androidx.compose.runtime.CompositionLocalKt.CompositionLocalProvider(CompositionLocal.kt:228)
        at androidx.compose.material.SurfaceKt.Surface-F-jzlyU(Surface.kt:252)
        at androidx.compose.material.SurfaceKt.Surface-F-jzlyU(Surface.kt:110)
        at org.jetbrains.codeviewer.ui.filetree.FileTreeViewKt.FileTreeViewTabView(FileTreeView.kt:31)
        at org.jetbrains.codeviewer.ui.CodeViewerViewKt$CodeViewerView$2$1.invoke(CodeViewerView.kt:51)
        at org.jetbrains.codeviewer.ui.CodeViewerViewKt$CodeViewerView$2$1.invoke(CodeViewerView.kt:49)
        at androidx.compose.runtime.internal.ComposableLambdaImpl.invoke(ComposableLambda.jvm.kt:107)
        at androidx.compose.runtime.internal.ComposableLambdaImpl.invoke(ComposableLambda.jvm.kt:34)
        at org.jetbrains.codeviewer.ui.CodeViewerViewKt.ResizablePanel(CodeViewerView.kt:90)
        at org.jetbrains.codeviewer.ui.CodeViewerViewKt.access$ResizablePanel(CodeViewerView.kt:1)
        at org.jetbrains.codeviewer.ui.CodeViewerViewKt$CodeViewerView$2.invoke(CodeViewerView.kt:49)
        at org.jetbrains.codeviewer.ui.CodeViewerViewKt$CodeViewerView$2.invoke(CodeViewerView.kt:48)
        at androidx.compose.runtime.internal.ComposableLambdaImpl.invoke(ComposableLambda.jvm.kt:107)
        at androidx.compose.runtime.internal.ComposableLambdaImpl.invoke(ComposableLambda.jvm.kt:34)
        at org.jetbrains.codeviewer.util.VerticalSplittableKt.VerticalSplittable(VerticalSplittable.kt:31)
        at org.jetbrains.codeviewer.ui.CodeViewerViewKt.CodeViewerView(CodeViewerView.kt:41)
        at org.jetbrains.codeviewer.ui.MainViewKt$MainView$1$1$1.invoke(MainView.kt:31)
        at org.jetbrains.codeviewer.ui.MainViewKt$MainView$1$1$1.invoke(MainView.kt:30)
        at androidx.compose.runtime.internal.ComposableLambdaImpl.invoke(ComposableLambda.jvm.kt:107)
        at androidx.compose.runtime.internal.ComposableLambdaImpl.invoke(ComposableLambda.jvm.kt:34)
        at androidx.compose.material.SurfaceKt$Surface$6.invoke(Surface.kt:268)
        at androidx.compose.material.SurfaceKt$Surface$6.invoke(Surface.kt:255)
        at androidx.compose.runtime.internal.ComposableLambdaImpl.invoke(ComposableLambda.jvm.kt:107)
        at androidx.compose.runtime.internal.ComposableLambdaImpl.invoke(ComposableLambda.jvm.kt:34)
        at androidx.compose.runtime.CompositionLocalKt.CompositionLocalProvider(CompositionLocal.kt:228)
        at androidx.compose.material.SurfaceKt.Surface-F-jzlyU(Surface.kt:252)
        at androidx.compose.material.SurfaceKt.Surface-F-jzlyU(Surface.kt:110)
        at org.jetbrains.codeviewer.ui.MainViewKt$MainView$1$1.invoke(MainView.kt:30)
        at org.jetbrains.codeviewer.ui.MainViewKt$MainView$1$1.invoke(MainView.kt:29)
        at androidx.compose.runtime.internal.ComposableLambdaImpl.invoke(ComposableLambda.jvm.kt:107)
        at androidx.compose.runtime.internal.ComposableLambdaImpl.invoke(ComposableLambda.jvm.kt:34)
...
```

The `ClassCastException` seems to happen at this line in [`ComposableLambda.jvm.kt`](https://github.com/androidx/androidx/blob/androidx-main/compose/runtime/runtime/src/jvmMain/kotlin/androidx/compose/runtime/internal/ComposableLambda.jvm.kt#L107) in [Jetpack Compose](https://github.com/androidx/androidx/tree/androidx-main/compose):

```
val result = (_block as (c: Composer, changed: Int) -> Any?)(c, dirty)
```

Apparently, `org.jetbrains.codeviewer.ui.filetree.LambdaGroup` is the current type of `_block`, and is cast to `Function2<Composer, Int, Any>`.
The decompiled code contains the following:

```
Object obj = this._block;
...
Object result = ((Function2) TypeIntrinsics.beforeCheckcastToFunctionOfArity(obj, 2)).invoke(c2, Integer.valueOf(dirty));
```

where `TypeIntrinsics` is in the package `kotlin.jvm.internal`. The method [`beforeCheckcastToFunctionOfArity(Object, int)`](https://github.com/JetBrains/kotlin/blob/92d200e093c693b3c06e53a39e0b0973b84c7ec5/libraries/stdlib/jvm/runtime/kotlin/jvm/internal/TypeIntrinsics.java#L339) is decompiled as follows or can be found in the [Kotlin source code](https://github.com/JetBrains/kotlin/):

```
    public static Object beforeCheckcastToFunctionOfArity(Object obj, int arity) {
        if (obj != null && !isFunctionOfArity(obj, arity))
            ...
    }

    public static boolean isFunctionOfArity(Object obj, int arity) {
        return (obj instanceof Function) && getFunctionArity(obj) == arity;
    }
```

According to the above, either the lambda group is not considered to be of type `Function`, even though it implements `Function2`, which extends `Function`, or its arity is not equal to 2 ... The latter seems to be the cause of this issue, given the decompiled implementation of `getFunctionArity(Object)`: 

```
    public static int getFunctionArity(Object obj) {
        if (obj instanceof FunctionBase) {
            return ((FunctionBase) obj).getArity();
        }
        if (obj instanceof Function0) {
            return 0;
        }
        ...
    }
```

Two possible problems arise here: the lambda group implements multiple interfaces, so it can only return the arity of interfacde with the lowest arity. Second and more importantly, the lambda group extends the class `kotlin.jvm.internal.Lambda<R>` (without providing a specific type `R`, which in its turn implements `FunctionBase<R>`, and that is once again an extension of `Function<R>`. `getFunctionArity(...)` will therefore return the arity that is passed to the lambda super constructor. Currently, this arity is always set to 0, so that explains why casting to `Function2` fails ... the arity that is found is not 2, but 0.

**Comment by heckej** [comment]
Commit [196a07acc491987db63c097de0e91ce9ca6b0f2e](https://github.com/heckej/proguard/commit/196a07acc491987db63c097de0e91ce9ca6b0f2e) solves this issue by passing the arity as a constructor argument to the lambda group.

**Comment by heckej** [comment]
An old note on Kotlin lambda's on the JVM and retrieving their arity: https://github.com/JetBrains/kotlin/blob/master/spec-docs/function-types.md#isas
